services:
  - type: web
    name: kj-dance-studio
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install && node build-prod.js
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
